# Generated by Django 2.2.10 on 2021-09-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Polling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите название опроса', max_length=256, verbose_name='Название опроса')),
                ('start_date', models.DateField(help_text='Введите дату начала опроса', verbose_name='Дата начала опроса')),
                ('end_date', models.DateField(help_text='Введите дату окончания опроса', verbose_name='Дата окончания опроса')),
                ('description', models.TextField(help_text='Введите описание для опроса', verbose_name='Описание опроса')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст вопроса', verbose_name='Текст вопроса')),
                ('question_type', models.PositiveIntegerField(choices=[(3, 'Ответ с выбором нескольких вариантов'), (2, 'Ответ с выбором одного варианта'), (1, 'Текстовый ответ')], help_text='Выберите тип вопроса', verbose_name='Тип вопроса')),
                ('polling', models.ForeignKey(help_text='Выберите опрос, к которому относится данный вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.Polling', verbose_name='Опрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст варианта ответа', verbose_name='Текст варианта ответа')),
                ('question', models.ForeignKey(help_text='Введите вариант ответа на вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.Question', verbose_name='Вариант ответа на вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа на вопрос',
                'verbose_name_plural': 'Варианты ответа на вопрос',
            },
        ),
        migrations.CreateModel(
            name='ChoiceAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.PositiveIntegerField(help_text='Введите идентификатор респондента', verbose_name='Идентификатор респондента')),
                ('answer', models.ForeignKey(help_text='Выберите вариант ответа', on_delete=django.db.models.deletion.CASCADE, to='api.QuestionOption', verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(help_text='Выберите вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='choice_answers', to='api.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ с вариантами выбора',
                'verbose_name_plural': 'Ответы с вариантами выбора',
            },
        ),
        migrations.CreateModel(
            name='TextAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_id', models.PositiveIntegerField(help_text='Введите идентификатор респондента', verbose_name='Идентификатор респондента')),
                ('answer', models.CharField(help_text='Введите ответ на вопрос', max_length=256, verbose_name='Ответ на вопрос')),
                ('question', models.ForeignKey(help_text='Выберите вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='text_answers', to='api.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Текстовый ответ',
                'verbose_name_plural': 'Текстовые ответы',
                'unique_together': {('respondent_id', 'question')},
            },
        ),
    ]
